name: FASM Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup FASM
        uses: stevenwdv/setup-fasm@v1

      - name: Make project
        run: make

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 5. Upload tetris.com as release artifact
      - name: Upload tetris.com
        uses: softprops/action-gh-release@v1
        with:
          files: dist/tetris.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
