name: FASM Build

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup FASM
        uses: stevenwdv/setup-fasm@v1

      - name: Build project
        run: make

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >-
          gh release create ${{ github.ref_name }}
          "dist/tetris.com"
          --title "Version ${{ github.ref_name }}"
